name: Deploy code to QA or PROD
on:
  workflow_dispatch:
    inputs:
      gitRef:
        default: 'refs/heads/main'
        type: string
jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build code
        run: npm run build
      - name: fake deploy project
        run: echo "Deploying to STAGING..."
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build code
        run: npm run build
      - name: fake deploy project
        run: echo "Deploying to PROD..."
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
